[project]
name = "masked-tfm"
version = "0.1.0"
description = "Masked tabular foundation model exploration"
readme = "README.md"
requires-python = ">=3.12, <3.13" 
dependencies = [
    "torch==2.10.0",
    "numpy==2.4.2",
    "lightning==2.6.1"
]

[dependency-groups]
dev = [
  "ruff>=0.6.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
